name: Test UI

on: 
  pull_request:
    branches:
      - main

jobs:
  test_ui:
    runs-on: ubuntu-latest

    container:
      image: node:24

    steps:
      - name: Go to UI Folder
        run: cd ./ui

      - uses: actions/checkout@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1

      - name: Install dependencies
        run: pnpm install

      - name: Build Server
        run: pnpm run build 