name: Test UI

on: 
  pull_request:
    branches:
      - main

jobs:
  test_ui:
    runs-on: ubuntu-latest
    container:
      image: node:24
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install

      - name: Build Server
        run: pnpm run build 