name: Test UI

on: 
  push:
    branches:
      - develop

jobs:
  test_ui:
    runs-on: ubuntu-latest

    container:
      image: node:24

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1

      - name: Install dependencies
        run: pnpm install
        working-directory: ui

      - name: Build UI
        run: pnpm run build 
        working-directory: ui